name = "TwoBandHamiltonians"
uuid = "f4e502db-bf3f-4ab5-bf0e-54b0a4831990"
authors = ["Wolfgang Hogger"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
